const shell = require('shelljs')
shell.cd('public')
shell.exec('git init')
shell.exec('git add .')
shell.exec('git commit -m "deploy"')
shell.exec('git branch -M master')
shell.exec('git remote add origin git@github.com:ALittleSuperman/blog-static.git')
shell.exec('git push -u --force origin master')
shell.rm('-rf', '.git/')
shell.exec('curl --location --request GET --X GET \'http://api.liuyongzhi.cn/deploy/blog-static\' \\\n' +
    '--header \'User-Agent: Apipost client Runtime/+https://www.apipost.cn/\'')
shell.cd('../')
shell.rm('-rf', 'public')
shell.exit()