# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # prevnext: 文章末尾的上一页与下一页
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/favicon.png
  author_nickname: Keller
  path: /

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 链接信息
link: 
  # name: 名称
  # icon: 图标，目前仅支持IconFont部分图标
  # path: 地址
  # target: 跳转方式
  -
    name: github
    icon: github
    path: https://github.com/ALittleSuperman
    target: _blank
  -
    name: email
    icon: envelope
    path: mailto:yongzhi1.liu@gmail.com

# 页脚信息
footer:
  -
    name: 路漫漫其修远兮，吾将上下而求索
    path: https://www.liuyongzhi.cn/

# 文章搜索
search:
  enable: true
  placeholder: 
